### ISSUE TITLE
new regristaion error

### ISSUE THREAD

**Issue by harsha2108k** [sidduganeshsid/A-Blockchain-Based-Autonomous-Decentralized-Online-Social-Network#3]
whenever i want to create a new user there is a internal server issue.I tried to solve the error but it is generating more errors.can you please help me in solving this errors.
![image](https://github.com/sidduganeshsid/A-Blockchain-Based-Autonomous-Decentralized-Online-Social-Network/assets/91387760/0e5d0d89-e4d2-4eef-b595-101f4f821b60)

**Comment by sidduganeshsid** [comment]
new registration is working fine. U need work with the Tomcat 7

**Comment by sidduganeshsid** [comment]
java 8

**Comment by harsha2108k** [comment]
can you help.with this error, now i installed tomcat 7,Java 8.but still i am having same issue
only user registration is not working, everything is fine
